let precio=500;
let cantidad= 4;
let porcentajeDescuento= 0.20;
let porcentajeImpuesto= 0.40;
let subtotal = (precio * cantidad);
let valorDescuento = (subtotal * porcentajeDescuento);
let baseGravable = (subtotal - valorDescuento);
let impuesto = (baseGravable * porcentajeImpuesto);
let total = (baseGravable + impuesto);
let puntosCliente= 100;
puntosCliente+= 50;
let envioGratis = (total > 1000);
let tieneMembresia = true;
let beneficioPremium = (tieneMembresia && envioGratis);
console.log("     Recibo     ");
console.log(`Subtotal: $${subtotal.toFixed(2)}`);
console.log(`Descuento aplicado: $${valorDescuento.toFixed(2)}`);
console.log(`Base Gravable: $${baseGravable.toFixed(2)}`);
console.log(`Impuesto: $${impuesto.toFixed(2)}`);
console.log(`Total a pagar: $${total.toFixed(2)}`);
console.log(`¿Tiene Envío Gratis?: ${envioGratis}`);
console.log(`Beneficio Premium: ${beneficioPremium}`);
console.log(`Puntos Totales del Cliente: ${puntosCliente}`);