Uso de Map Estricto reemplazamos los objetos planos de javaScript por la estructura de datos "Map" 

Esto nos permite usar de forma segura los métodos ".set()", ".get()" y ".has()" para gestionar los contadores sin colisionar con nombres de propiedades heredadas del sistema

Limpieza de Signos y Tildes se aplico una expresion regular para remover puntos, comas y caracteres especiales, forzando la conversion a minusculas antes del corte por espacios de este modo garantizamos que las palabras se acumulen uniformemente

Agrupación Avanzada estructuramos un segundo mapa donde la clave es el numero de caracteres y el valor corresponde a un arreglo dinamico clasificamos las palabras recolectadas sin repetir registros idénticos en una misma lista